// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvwndjzoxwmjqoprvxzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2d25kanpveHdtanFvcHJ2eHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjI2NzEsImV4cCI6MjA3NDEzODY3MX0.Dylcsts_k5CXgBfBjwPPP9vkTi1XPePmg09bfxQqF3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});